# Generated by Django 3.0.3 on 2020-03-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200307_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image_url',
        ),
    ]
