# Generated by Django 3.0.3 on 2020-03-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='image',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
