# Generated by Django 3.0.3 on 2020-03-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_remove_ingredient_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default='Test menu', max_length=50),
            preserve_default=False,
        ),
    ]
