# Generated by Django 3.0.3 on 2020-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
