# Generated by Django 3.0.3 on 2020-04-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='descriptions',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
